a=int(input("Enter number: "))
b=int(input("Enter number: "))
print('Sum: ',a+b)
print('Difference: ',a-b)
print('Product: ',a*b)
print('Division: ',a/b)
print('Modulus: ',a%b)
print('Floor Division: ',a//b)
print('Power: ', pow(a,b))
